// <auto-generated />
using System;
using KakeiboApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KakeiboApp.Migrations
{
    [DbContext(typeof(KakeiboDbContext))]
    partial class KakeiboDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KakeiboApp.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "cat-01",
                            BudgetLimit = 50000,
                            Icon = "🍚",
                            IsDefault = true,
                            Name = "食費"
                        },
                        new
                        {
                            Id = "cat-02",
                            BudgetLimit = 10000,
                            Icon = "🚃",
                            IsDefault = true,
                            Name = "交通費"
                        },
                        new
                        {
                            Id = "cat-03",
                            BudgetLimit = 15000,
                            Icon = "🧴",
                            IsDefault = true,
                            Name = "日用品"
                        },
                        new
                        {
                            Id = "cat-04",
                            BudgetLimit = 20000,
                            Icon = "💡",
                            IsDefault = true,
                            Name = "光熱費"
                        },
                        new
                        {
                            Id = "cat-05",
                            BudgetLimit = 20000,
                            Icon = "🎮",
                            IsDefault = true,
                            Name = "娯楽"
                        },
                        new
                        {
                            Id = "cat-06",
                            BudgetLimit = 10000,
                            Icon = "🏥",
                            IsDefault = true,
                            Name = "医療費"
                        },
                        new
                        {
                            Id = "cat-07",
                            BudgetLimit = 15000,
                            Icon = "👕",
                            IsDefault = true,
                            Name = "衣服"
                        },
                        new
                        {
                            Id = "cat-08",
                            BudgetLimit = 10000,
                            Icon = "📱",
                            IsDefault = true,
                            Name = "通信費"
                        },
                        new
                        {
                            Id = "cat-09",
                            BudgetLimit = 0,
                            Icon = "💴",
                            IsDefault = true,
                            Name = "給料"
                        },
                        new
                        {
                            Id = "cat-10",
                            BudgetLimit = 10000,
                            Icon = "📦",
                            IsDefault = true,
                            Name = "その他"
                        });
                });

            modelBuilder.Entity("KakeiboApp.Models.CreditCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosingDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("KakeiboApp.Models.FixedExpense", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FixedExpenses");
                });

            modelBuilder.Entity("KakeiboApp.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BillingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
